language: java
sudo: required
dist: trusty
addons:
  chrome: stable

before_install:
  - wget https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d .
  - rm chromedriver_linux64.zip
  - sudo mv -f chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  
script:
  - mvn clean install -Dgoogle.chrome=/usr/bin/google-chrome-stable -Ddevice=$EMULATED_DEVICE

after_script:
  - cat target/surefire-reports/*.txt

env:
  - CHROME_BINARY_PATH=/usr/bin/google-chrome-stable
  - EMULATED_DEVICE=Nexus5
  - EMULATED_DEVICE=iPhone6/7/8
  - EMULATED_DEVICE=GalaxyS5
  - EMULATED_DEVICE=iPad
  - EMULATED_DEVICE=