language: java
sudo: required
dist: trusty
addons:
  chrome: stable

before_install:
  - wget https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d .
  - rm chromedriver_linux64.zip
  - sudo mv -f chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - export CHROME_BINARY_PATH=$(whereis google-chrome-stable)

script:
  - whereis google-chrome-stable
  - whereis chromedriver
