language: java
sudo: required
dist: trusty
addons:
  chrome: stable

before_install:
  - wget https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d resources
  - # start your web application and listen on `localhost`
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

before_script: sudo chmod +x resources/chromedriver