language: java

dist: trusty

addons:
	chrome: stable

sudo: required

before_install:
	- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script: sudo chmod +x resources/chromedriver

env:
 - WEB_DRIVER_URL=http://localhost:9222